# Generated by Django 3.1.3 on 2020-11-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.CharField(default='derp', max_length=500),
            preserve_default=False,
        ),
    ]
