# Generated by Django 3.1.3 on 2020-11-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='uuid',
            field=models.IntegerField(default=248649108335374564610573148520017090153),
        ),
    ]
