# Generated by Django 3.1.3 on 2020-11-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_thread_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='uuid',
            field=models.BigIntegerField(default=114290426136205794965451442818664181097),
        ),
    ]
