# Generated by Django 3.1.3 on 2020-11-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0005_auto_20201113_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='uuid',
            field=models.UUIDField(default=153906628530328346009103576073083990672, editable=False),
        ),
    ]
