# Generated by Django 3.1.3 on 2020-11-13 10:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0007_auto_20201113_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c9580b6f-c694-4b4e-ba82-600f3fc2ece3'), editable=False),
        ),
    ]
