# Generated by Django 3.1.3 on 2020-11-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0008_auto_20201113_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='uuid',
            field=models.TextField(default='141753687573888091008597862954747721479', editable=False),
        ),
    ]
